import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";

import localFont from 'next/font/local';

//TODO: Do import from "@repo/ui/fonts/Geist[wght].ttf" 
const geist = localFont({ src: "../../public/fonts/Geist[wght].ttf" })

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={geist.className}>{children}</body>
    </html>
  );
}
